cmake_minimum_required(VERSION 3.20)

project(inc_puzzle_gen CXX)

enable_language(CXX)

list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR})

if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE "Release")
endif()
message(STATUS "Build type: ${CMAKE_BUILD_TYPE}")

# Visual Studio compiler with static runtime libraries
if(MSVC AND MT)
  set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")
  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MTd")
  set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} /MT")
  set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} /MTd")
endif()
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

find_package(GUROBI REQUIRED)

include_directories(${GUROBI_INCLUDE_DIRS})
set(CMAKE_CXX_STANDARD 20)

# list source files here
set(sources 
    src/vorosketch-037.cpp
    src/solver.cpp
    src/main.cpp
    src/instance.cpp
    src/options.cpp
    src/benchmark.cpp
)

add_executable(${CMAKE_PROJECT_NAME} ${sources})

#set(CMAKE_CXX_COMPILER "C:/msys64/clang64/bin/clang++.exe")

target_link_libraries(${CMAKE_PROJECT_NAME} optimized ${GUROBI_CXX_LIBRARY}
                      debug ${GUROBI_CXX_DEBUG_LIBRARY})

target_link_libraries(${CMAKE_PROJECT_NAME} ${GUROBI_LIBRARY})

if(${CMAKE_SOURCE_DIR} STREQUAL ${CMAKE_CURRENT_SOURCE_DIR})
  include(FeatureSummary)
  feature_summary(WHAT ALL)
endif()
